add_executable(image_cache_tests image_cache_tests.cpp)
target_link_libraries(image_cache_tests PRIVATE vulkan_3dgs_core)
add_test(NAME image_cache_tests COMMAND image_cache_tests)

add_executable(training_ssim_tests training_ssim_tests.cpp)
add_test(NAME training_ssim_tests COMMAND training_ssim_tests)

add_executable(training_validation_tests training_validation_tests.cpp)
target_link_libraries(training_validation_tests PRIVATE vulkan_3dgs_core)
add_test(NAME training_validation_tests COMMAND training_validation_tests)
